  version: "3"
  services:
    postgres:
      container_name: "${NAME}-postgres"
      image: postgres:13-alpine
      env_file: .env
      ports:
        - "5432:5432"
    backend:
      container_name: "${NAME}-backend"
      image: postgrest/postgrest
      env_file: .env
      ports:
        - "3000:3000"
      depends_on:
        - postgres
    frontend:
      container_name: "${NAME}-frontend"
      build: frontend
      ports:
        - "8080:80"
      links:
        - backend
    mgmt:
      container_name: "${NAME}-mgmt"
      # Unfortunately we cannot build this image directly from the compose file
      # since docker-compose only supports building image with Dockerfiles and
      # this image is build with nix.
      image: "ghcr.io/koenw/${NAME}-mgmt:latest"
      env_file: .env
      depends_on:
        - postgres
    swagger:
      container_name: "${NAME}-swagger"
      image: "swaggerapi/swagger-ui"
      depends_on:
        - backend
      environment:
        - "URL=http://localhost:3000"
      ports:
        - "8088:8080"
