  version: "3"
  services:
    postgres:
      container_name: "${NAME}-postgres"
      image: postgres:13-alpine
      env_file: .env
      ports:
        - "5432:5432"
    backend:
      container_name: "${NAME}-backend"
      image: postgrest/postgrest
      env_file: .env
      ports:
        - "3000:3000"
      depends_on:
        - postgres
